using JC.Web.UI.Framework;

namespace JC.FileStorage.Web.Framework;

/// <summary>
/// Tailwind CSS classes for JC.FileStorage.Web's tag helpers, chosen to reproduce Bootstrap 5's
/// appearance as closely as utilities allow. Selected when <see cref="UIFramework.Tailwind"/> is
/// configured.
/// </summary>
/// <remarks>
/// Targets Tailwind v4 and assumes Preflight.
/// <para>
/// <b>Every class here must be declared to Tailwind.</b> Utilities are generated by scanning source
/// files, and these values live in a compiled assembly it never reads, so <c>@source</c> over the
/// application's markup does not reach them.
/// </para>
/// <para>
/// <b>Adding or changing a value here means updating <c>jc-filestorage.tailwind.css</c>.</b> That
/// file declares every class this dictionary emits; a value added here and not there renders with a
/// valid class name and no CSS behind it.
/// </para>
/// </remarks>
public sealed class TailwindFileStorageDictionary : IFileStorageFrameworkDictionary
{
    /// <inheritdoc />
    /// <remarks>Bootstrap's <c>form-text</c> is muted, small and spaced from the control above it.</remarks>
    public UploadConstraintsClasses UploadConstraints { get; } = new()
    {
        Container = "mt-1 text-sm text-gray-500"
    };
}
