using JC.Web.UI.HTML;

namespace JC.Web.UI.Framework;

/// <summary>
/// Tailwind CSS classes for JC.Web's tag helpers and HTML builders, chosen to reproduce Bootstrap 5's
/// appearance as closely as utilities allow. Selected when <see cref="UIFramework.Tailwind"/> is
/// configured.
/// </summary>
/// <remarks>
/// Targets Tailwind v4 and assumes Preflight, whose anchor reset is what lets breadcrumb and
/// pagination links take their colour from the element around them.
/// <para>
/// <b>Every class here must be declared to Tailwind.</b> Utilities are generated by scanning source
/// files, and these values live in a compiled assembly it never reads, so <c>@source</c> over the
/// application's markup does not reach them. The practical fix is an application file repeating
/// these values verbatim for <c>@source</c> to scan — the generated-content and <c>[&amp;&gt;a]:…</c>
/// entries are impractical to list inline. <see cref="CustomJCTailwindDictionary"/> needs almost none
/// of this, since the framework it targets ships its own CSS.
/// </para>
/// </remarks>
public sealed class TailwindDictionary : IWebFrameworkDictionary
{
    /// <inheritdoc />
    public AlertClasses Alert { get; } = new()
    {
        Container = "relative mb-4 rounded-md border px-4 py-3",
        Dismissible = "pr-12",

        // Bootstrap's cross is a background image; utilities can't carry one, so it's
        // generated content — the button the helper emits has no children.
        CloseButton =
            "absolute top-0 right-0 px-4 py-3 text-xl leading-none opacity-50 hover:opacity-75 before:content-['×']",
        Variants = new Dictionary<AlertType, string>
        {
            [AlertType.Success] = "border-green-300 bg-green-100 text-green-900",
            [AlertType.Warning] = "border-amber-300 bg-amber-100 text-amber-900",
            [AlertType.Error] = "border-red-300 bg-red-100 text-red-900",
            [AlertType.Info] = "border-sky-300 bg-sky-100 text-sky-900"
        }
    };

    /// <inheritdoc />
    public BreadcrumbClasses Breadcrumb { get; } = new()
    {
        // Styled on the list rather than the nav, as in Bootstrap. Separator is generated
        // content, suppressed on the first item.
        List = "mb-4 flex list-none flex-wrap items-center p-0",
        Item = "flex items-center text-blue-600 before:mr-2 before:text-gray-500 before:content-['/'] first:before:content-none",
        ActiveItem = "flex items-center text-gray-500 before:mr-2 before:text-gray-500 before:content-['/'] first:before:content-none"
    };

    /// <inheritdoc />
    /// <remarks>
    /// The state class lands on the <c>&lt;li&gt;</c>, so these reach the link with a child variant.
    /// The negative offset joins the borders as Bootstrap does.
    /// </remarks>
    public PaginationClasses Pagination { get; } = new()
    {
        List = "flex list-none items-center -space-x-px p-0 "
               + "[&>li:first-child>a]:rounded-l-md [&>li:last-child>a]:rounded-r-md",
        ActiveItem = "z-10 [&>a]:border-blue-600 [&>a]:bg-blue-600 [&>a]:text-white [&>a]:hover:bg-blue-600",
        DisabledItem = "[&>a]:pointer-events-none [&>a]:bg-white [&>a]:text-gray-400",
        Link = "relative block border border-gray-300 px-3 py-2 text-blue-600 hover:bg-gray-100 hover:text-blue-800"
    };

    /// <inheritdoc />
    public TableClasses Table { get; } = new()
    {
        // Rules on the row rather than the cells, leaving head/body empty so the builder
        // emits bare thead/tbody as it does under Bootstrap.
        Table = "mb-4 w-full border-collapse text-left",
        Row = "border-b border-gray-200",
        HeaderCell = "border-b-2 border-gray-300 px-2 py-2 align-top font-semibold",
        Cell = "px-2 py-2 align-top"
    };

    /// <inheritdoc />
    /// <remarks>
    /// The colour is a Tailwind fragment, not a Bootstrap contextual name — <c>colour="sky-600"</c>
    /// is the equivalent of <c>colour="info"</c>. <see cref="BugReporterClasses.FeedbackFormat"/> is
    /// substituted in the browser with the outcome word, so the theme must define
    /// <c>success</c>/<c>warning</c>/<c>danger</c> colours; leave it empty if it cannot.
    /// </remarks>
    public BugReporterClasses BugReporter { get; } = new()
    {
        ToggleButton = "print:hidden",
        PanelFormat = "rounded-md border border-{0} bg-white shadow-lg print:hidden",
        DefaultColour = "red-600",
        PanelBody = "p-3",
        TitleFormat = "mb-2 text-base font-semibold text-{0}",
        Field = "mb-2",
        Label = "mb-1 block text-sm",
        Select = "block w-full rounded-md border border-gray-300 px-2 py-1 text-sm",
        TextArea = "block w-full rounded-md border border-gray-300 px-2 py-1 text-sm",
        Hidden = "hidden",
        Actions = "flex justify-between",
        CancelButton = "rounded-md border border-gray-500 px-2 py-1 text-sm text-gray-600 hover:bg-gray-500 hover:text-white",
        SubmitButtonFormat = "rounded-md bg-{0} px-2 py-1 text-sm text-white hover:opacity-90",
        FeedbackFormat = "mb-2 rounded-md border border-{0}-300 bg-{0}-100 px-2 py-1 text-sm text-{0}-900"
    };

    /// <inheritdoc />
    /// <remarks>
    /// Tailwind has no equivalent of Bootstrap's per-component <c>active</c>/<c>disabled</c> states,
    /// so these are generic approximations rather than reproductions.
    /// </remarks>
    public StateClasses State { get; } = new()
    {
        Active = "font-semibold",
        Disabled = "pointer-events-none opacity-50"
    };
}
