using JC.Communication.Notifications.Models;
using JC.Web.UI.Framework;

namespace JC.Communication.Web.Framework;

/// <summary>
/// Tailwind CSS classes for JC.Communication.Web's tag helpers, chosen to reproduce Bootstrap 5's
/// appearance as closely as utilities allow. Selected when <see cref="UIFramework.Tailwind"/> is
/// configured.
/// </summary>
/// <remarks>
/// Targets Tailwind v4 and assumes Preflight. Preflight resets headings to inherit their size, which
/// is why <see cref="ContactFormClasses.Heading"/> restores it — under Bootstrap the <c>h4</c> the
/// tag helper emits carries its own.
/// <para>
/// <b>Every class here must be declared to Tailwind.</b> Utilities are generated by scanning source
/// files, and these values live in a compiled assembly it never reads, so <c>@source</c> over the
/// application's markup does not reach them.
/// </para>
/// <para>
/// <b>Adding or changing a value here means updating <c>jc-communication.tailwind.css</c>.</b> That
/// file declares every class this dictionary emits; a value added here and not there renders with a
/// valid class name and no CSS behind it.
/// </para>
/// <para>
/// Contextual colours are Tailwind fragments rather than Bootstrap contextual names —
/// <c>button-colour="sky-600"</c> is the equivalent of <c>button-colour="info"</c>, and the dropdown's
/// <c>align</c> is a placement utility such as <c>right-0</c> rather than <c>end</c>.
/// </para>
/// </remarks>
public sealed class TailwindCommunicationDictionary : ICommunicationFrameworkDictionary
{
    /// <inheritdoc />
    /// <remarks>
    /// The menu is <c>hidden</c> until something shows it, as Bootstrap's is. The tag helper emits
    /// <c>data-bs-toggle</c> either way, so an application on Tailwind supplies the few lines of
    /// JavaScript that toggle the class.
    /// </remarks>
    public NotificationDropdownClasses NotificationDropdown { get; } = new()
    {
        Container = "relative inline-block",
        BellButton = "relative inline-flex items-center px-3 py-2 text-blue-600 hover:text-blue-800",

        // The translate pair reproduces Bootstrap's translate-middle.
        BadgeFormat = "absolute top-0 left-full -translate-x-1/2 -translate-y-1/2 rounded-full "
                      + "bg-{0} px-2 py-0.5 text-xs font-semibold text-white",
        DefaultBadgeColour = "red-600",
        ScreenReaderOnly = "sr-only",

        // {0} is a placement utility, not a Bootstrap alignment word. The menu's width comes from an
        // inline style on the element, so no width utility is set here.
        MenuFormat = "absolute z-50 mt-1 hidden rounded-md border border-gray-200 bg-white shadow-lg {0}",
        DefaultAlign = "right-0",
        EmptyItem = "block px-3 py-3 text-center text-sm text-gray-500",
        Item = "flex items-start gap-2 border-b border-gray-200 px-3 py-2 text-gray-900 hover:bg-gray-100",

        // {0} is the whole icon class from the icon dictionary, base class included — this format
        // must not add one of its own, since Font Awesome has no equivalent of "bi".
        ItemIconFormat = "{0} mt-1 text-{1}",
        ItemContent = "grow overflow-hidden",
        ItemTitle = "truncate font-semibold",
        ItemBody = "truncate text-sm text-gray-500",
        ItemTime = "text-sm text-gray-500",
        UnreadDotFormat = "mt-2 rounded-full bg-{0}",

        // The element is an <hr>, whose border Preflight strips — hence a border rather than a colour.
        Divider = "m-0 border-t border-gray-200",
        FooterLink = "block px-3 py-2 text-center text-blue-600 hover:bg-gray-100"
    };

    /// <inheritdoc />
    public NotificationBadgeClasses NotificationBadge { get; } = new()
    {
        Container = "relative inline-flex",
        BadgeFormat = "absolute top-0 left-full -translate-x-1/2 -translate-y-1/2 rounded-full "
                      + "bg-{0} px-2 py-0.5 text-xs font-semibold text-white",
        DefaultBadgeColour = "red-600",
        ScreenReaderOnly = "sr-only"
    };

    /// <inheritdoc />
    public NotificationToastClasses NotificationToast { get; } = new()
    {
        ContainerFormat = "fixed z-50 p-3 {0}",
        DefaultPosition = "top-0 right-0",
        Toast = "mb-2 w-80 max-w-full rounded-md border border-gray-200 bg-white shadow-lg",
        Header = "flex items-center gap-2 border-b border-gray-200 px-3 py-2",
        HeaderIconFormat = "{0} text-{1}",
        HeaderTitle = "mr-auto font-semibold",
        HeaderTime = "text-sm text-gray-500",

        // Bootstrap's cross is a background image; utilities can't carry one, so it's generated
        // content — the button the tag helper emits has no children.
        CloseButton = "ml-1 text-xl leading-none text-gray-500 hover:text-gray-900 before:content-['×']",
        Body = "px-3 py-2"
    };

    /// <inheritdoc />
    public MessageThreadClasses MessageThread { get; } = new()
    {
        Container = "flex flex-col gap-2 p-3",
        Header = "flex items-center gap-2 border-b border-gray-200 p-3",
        HeaderAvatar = "rounded-full",
        HeaderName = "font-semibold",
        MemberBadge = "rounded-full bg-gray-500 px-2 py-0.5 text-xs font-semibold text-white",
        ReplyPreview = "mb-1 border-l-2 border-gray-300 pl-2 text-sm text-gray-500",
        ReplyName = "font-semibold",
        SenderName = "text-sm font-semibold",
        BubbleFormat = "rounded-lg bg-{0} px-3 py-2 text-{1}",
        MessageTime = "text-right text-sm opacity-75",
        SentAlign = "self-end",
        ReceivedAlign = "self-start",
        DefaultSentColour = "blue-600",
        DefaultReceivedColour = "gray-100",
        DefaultSentTextColour = "white",
        DefaultReceivedTextColour = "gray-900"
    };

    /// <inheritdoc />
    public ChatListClasses ChatList { get; } = new()
    {
        // overflow-hidden clips the first and last rows to the rounded corners, as Bootstrap's
        // list-group does.
        Container = "flex flex-col overflow-hidden rounded-md border border-gray-200",
        Empty = "py-3 text-center text-gray-500",
        Item = "flex items-center gap-3 border-b border-gray-200 px-3 py-2 text-gray-900 "
               + "last:border-b-0 hover:bg-gray-100",
        Avatar = "shrink-0",
        AvatarImage = "rounded-full",
        AvatarIcon = "flex items-center justify-center rounded-full",
        AvatarFallback = "flex items-center justify-center rounded-full bg-gray-200",

        // A colour value rather than a class — it is set through the inline style that sizes the
        // avatar. A literal rather than a theme variable, since Tailwind emits theme variables only
        // for the values it generates utilities for.
        AvatarIconBackground = "#e5e7eb",
        Content = "grow overflow-hidden",
        NameRow = "flex justify-between",
        Name = "truncate font-semibold",
        Time = "ml-2 shrink-0 text-gray-500",
        Preview = "truncate text-sm text-gray-500",
        PreviewSender = "font-medium",
        UnreadBadgeFormat = "shrink-0 self-center rounded-full bg-{0} px-2 py-0.5 text-xs font-semibold text-white",
        DefaultUnreadBadgeColour = "blue-600"
    };

    /// <inheritdoc />
    public ChatInputClasses ChatInput { get; } = new()
    {
        Form = "border-t border-gray-200 p-3",
        ReplyBar = "mb-2 flex items-center rounded-md border-l-2 border-blue-600 bg-gray-100 py-1 pl-2",
        ReplyText = "grow truncate text-sm",
        ReplyName = "font-semibold",
        ReplyClose = "ml-2 text-xl leading-none text-gray-500 hover:text-gray-900 before:content-['×']",
        InputRow = "flex items-end",
        TextArea = "block w-full rounded-md border border-gray-300 px-2 py-1",
        SendButtonFormat = "ml-2 self-end rounded-md bg-{0} px-3 py-2 text-sm text-white hover:opacity-90",
        DefaultButtonColour = "blue-600"
    };

    /// <inheritdoc />
    public ContactFormClasses ContactForm { get; } = new()
    {
        // Preflight strips the heading's size and weight, so they are restored here.
        Heading = "mb-3 text-lg font-semibold",
        Field = "mb-3",
        Label = "mb-1 block text-sm",
        Input = "block w-full rounded-md border border-gray-300 px-2 py-1",
        TextArea = "block w-full rounded-md border border-gray-300 px-2 py-1",
        SubmitButtonFormat = "rounded-md bg-{0} px-3 py-2 text-sm text-white hover:opacity-90",
        DefaultButtonColour = "blue-600"
    };

    /// <inheritdoc />
    /// <remarks>
    /// Tailwind colour fragments, matching the palette
    /// <see cref="JC.Web.UI.Framework.TailwindDictionary"/> uses for its alert variants.
    /// </remarks>
    public NotificationTypeClasses NotificationTypes { get; } = new()
    {
        Colours = new Dictionary<NotificationType, string>
        {
            [NotificationType.Message] = "blue-600",
            [NotificationType.Info] = "sky-600",
            [NotificationType.Success] = "green-600",
            [NotificationType.Warning] = "amber-500",
            [NotificationType.Error] = "red-600",
            [NotificationType.System] = "gray-500",
            [NotificationType.Task] = "blue-600"
        },
        ColourFallback = "gray-500"
    };

    /// <inheritdoc />
    public ChatParticipantsClasses ChatParticipants { get; } = new()
    {
        Container = "flex items-center gap-1",
        Avatar = "flex items-center justify-center rounded-full bg-blue-100 font-semibold text-blue-700",
        Overflow = "flex items-center justify-center rounded-full bg-gray-200 font-semibold text-gray-500"
    };
}
